# Generated by Django 4.2.9 on 2024-03-06 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
