# Generated by Django 4.2.9 on 2024-03-06 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0004_remove_productimage_product_delete_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stripe_product')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('img_main', models.ImageField(blank=True, null=True, upload_to='product')),
                ('img_1', models.ImageField(blank=True, null=True, upload_to='product')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='product')),
                ('img_3', models.ImageField(blank=True, null=True, upload_to='product')),
                ('img_4', models.ImageField(blank=True, null=True, upload_to='product')),
                ('img_5', models.ImageField(blank=True, null=True, upload_to='product')),
                ('short_description', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('promo', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_stripe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='common.productstripe')),
                ('tags', models.ManyToManyField(blank=True, to='common.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
