# Generated by Django 4.2.9 on 2024-03-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstripe',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
