# Generated by Django 4.2.9 on 2024-03-11 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_cart_is_ordered_alter_productstripe_image_order'),
        ('common', '0008_stripecredentials'),
    ]

    operations = [
    ]
