# Generated by Django 4.2.9 on 2024-03-19 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_productprops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='country_of_origin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
