# Generated by Django 4.2.9 on 2024-03-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_remove_product_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
