# Generated by Django 4.2.9 on 2024-03-19 05:54

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_product_url_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('site_name', 'Site name'), ('copyright', 'Copyright'), ('stripe_pub_key', 'Stripe publishable key'), ('stripe_sec_key', 'Stripe secret key'), ('social_twitter', 'Social twitter'), ('social_instagram', 'Social instagram'), ('social_github', 'Social github'), ('social_facebook', 'Social facebook'), ('legal_privacy', 'Legal privacy'), ('legal_terms', 'Legal terms')], max_length=255)),
                ('value', models.TextField(blank=True, null=True)),
                ('value_html', django_quill.fields.QuillField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
