# Generated by Django 4.2.9 on 2024-03-19 08:49

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_settings_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='test', editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='test', editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
    ]
