# Generated by Django 4.2.9 on 2024-03-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_product_slug_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='type',
            field=models.CharField(choices=[('site_name', 'Site name'), ('copyright', 'Copyright'), ('stripe_pub_key', 'Stripe publishable key'), ('stripe_sec_key', 'Stripe secret key'), ('social_twitter', 'Social twitter'), ('social_instagram', 'Social instagram'), ('social_github', 'Social github'), ('social_facebook', 'Social facebook'), ('legal_privacy', 'Legal privacy'), ('legal_terms', 'Legal terms'), ('hero_video', 'Hero video')], max_length=255, unique=True),
        ),
    ]
